/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisarRouteImport } from './routes/analisar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as LaudoRouteImport } from './routes/laudo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisarRoute = AnalisarRouteImport.update({
  id: '/analisar',
  path: '/analisar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const LaudoRoute = LaudoRouteImport.update({
  id: '/laudo',
  path: '/laudo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisar': typeof AnalisarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/laudo': typeof LaudoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisar': typeof AnalisarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/laudo': typeof LaudoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisar': typeof AnalisarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/laudo': typeof LaudoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analisar' | '/cadastro' | '/entrar' | '/laudo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analisar' | '/cadastro' | '/entrar' | '/laudo'
  id: '__root__' | '/' | '/analisar' | '/cadastro' | '/entrar' | '/laudo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisarRoute: typeof AnalisarRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  LaudoRoute: typeof LaudoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisar': {
      id: '/analisar'
      path: '/analisar'
      fullPath: '/analisar'
      preLoaderRoute: typeof AnalisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laudo': {
      id: '/laudo'
      path: '/laudo'
      fullPath: '/laudo'
      preLoaderRoute: typeof LaudoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisarRoute: AnalisarRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  LaudoRoute: LaudoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
